/* Board definition for the touch version of Waveshare ESP32-S3-Touch-LCD-1.47. */
#ifndef WAVESHARE_TOUCH_LCD_1_47_H
#define WAVESHARE_TOUCH_LCD_1_47_H

#define BOARD_LCD_HOST SPI2_HOST
#define BOARD_LCD_SCLK 38
#define BOARD_LCD_MOSI 39
#define BOARD_LCD_CS 21
#define BOARD_LCD_DC 45
#define BOARD_LCD_RST 40
#define BOARD_LCD_BACKLIGHT 46
#define BOARD_LCD_PIXEL_CLOCK_HZ (80 * 1000 * 1000)

#define BOARD_TOUCH_I2C_PORT 0
#define BOARD_TOUCH_SDA 42
#define BOARD_TOUCH_SCL 41
#define BOARD_TOUCH_INT 47
#define BOARD_TOUCH_RST 48
#define BOARD_TOUCH_ADDRESS 0x63
#define BOARD_TOUCH_CLOCK_HZ (400 * 1000)

#define BOARD_USB_D_MINUS 19
#define BOARD_USB_D_PLUS 20

#define BOARD_PANEL_NATIVE_WIDTH 172
#define BOARD_PANEL_NATIVE_HEIGHT 320
/* 90-degree landscape, USB-C on the right. LCD and touch have different
 * native axis conventions; touch mirrors apply AFTER the software XY swap. */
#define BOARD_PANEL_SWAP_XY 1
#define BOARD_PANEL_MIRROR_X 1
#define BOARD_PANEL_MIRROR_Y 0
#define BOARD_PANEL_INVERT_COLOR 1
#define BOARD_TOUCH_SWAP_XY 1
#define BOARD_TOUCH_MIRROR_X 0
#define BOARD_TOUCH_MIRROR_Y 0
#define BOARD_SCREEN_WIDTH \
  (BOARD_PANEL_SWAP_XY ? BOARD_PANEL_NATIVE_HEIGHT : BOARD_PANEL_NATIVE_WIDTH)
#define BOARD_SCREEN_HEIGHT \
  (BOARD_PANEL_SWAP_XY ? BOARD_PANEL_NATIVE_WIDTH : BOARD_PANEL_NATIVE_HEIGHT)
#define BOARD_PANEL_GAP_X 0
#define BOARD_PANEL_GAP_Y 34

#define BOARD_OLED_SCALE 2
#define BOARD_OLED_X 32
#define BOARD_OLED_Y 22
#define BOARD_OLED_WIDTH 256
#define BOARD_OLED_HEIGHT 128

#define BOARD_CANCEL_X_MIN 0
#define BOARD_CANCEL_X_MAX 111
#define BOARD_CONFIRM_X_MIN 208
#define BOARD_CONFIRM_X_MAX 319
#define BOARD_ACTION_Y_MIN 112
#define BOARD_ACTION_Y_MAX 171
#define BOARD_TOUCH_DEBOUNCE_MS 15

#define BOARD_BACKLIGHT_DUTY_PERCENT 60
#define BOARD_BACKLIGHT_PWM_HZ 5000

#endif
