#pragma once
#define CFG_TUSB_MCU OPT_MCU_NONE
#define TUP_DCD_ENDPOINT_MAX 8
#define CFG_TUSB_OS OPT_OS_NONE
#define CFG_TUD_ENABLED 1
#define CFG_TUD_MAX_SPEED OPT_MODE_FULL_SPEED
#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUD_HID 0
#define CFG_TUD_VENDOR 0
